- include_vars: access.yml

- name: OAuth object
  kubernetes.core.k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        identityProviders:
          - ldap:
              attributes:
                email:
                  - mail
                id:
                  - dn
                name:
                  - cn
                preferredUsername:
                  - uid
              insecure: false
              url: >-
                ldaps://scoldap.epfl.ch:636/o=epfl,c=ch?uid?sub?(memberof={{_sgroup}})
            mappingMethod: claim
            name: scoldap
            type: LDAP
  vars:
    _sgroup: >-
      {{ lookup("scoldap",
      _group_name,
      by="cn", get="uniqueidentifier") }}
    _group_name: >-
      {{ openshift_oauth_admin_ldap_access_groups[inventory_hostname] }}

- name: Delete the kubeadmin account (`-t all.lockdown`)
  # The “never” tag doesn't actually work here; ask me how I know...
  when: >-
    ("all.lockdown" in ansible_run_tags)
    or
    ("openshift.config.auth.lockdown" in ansible_run_tags)
  kubernetes.core.k8s:
    state: absent
    kind: Secret
    namespace: kube-system
    name: kubeadmin
